version: "3.8"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    command: python main.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
#      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - local-dev
  worker:
    build: .
    command: celery --app tasks.celery worker
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
#      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - server
      - redis
    networks:
      - local-dev
  redis:
    image: redis:6-alpine
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - local-dev
networks:
  local-dev:
    external: true


    


